[workspace]
resolver = "2"
members = ["crates/structre", "crates/structre_proc_macros"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "ISC"
repository = "https://github.com/andrewbaxter/structre"
readme = "readme.md"
