[package]
name = "structre_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "mod.rs"

[features]
default = ["unicode"]
unicode = []

[dependencies]
litrs = "0.2.3"
proc-macro2 = "1.0.47"
quote = "1.0.21"
regex-syntax = "0.6.28"
syn = "1.0.103"
